# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_rename_link_to_reference_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='reference',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referencerequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
