# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_alter_referencefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreferencefeedback',
            name='objection',
        ),
        migrations.RemoveField(
            model_name='userreferencefeedback',
            name='useful',
        ),
        migrations.AlterField(
            model_name='referencereport',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_reports', to='annotation.Reference'),
        ),
    ]
