# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django

class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_rename_reference_to_annotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='reference_link',
            new_name='annotation_link',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='reference_link_title',
            new_name='annotation_link_title',
        ),
        migrations.RenameField(
            model_name='annotationreport',
            old_name='reference',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='annotationupvote',
            old_name='reference',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='historicalannotation',
            old_name='reference_link',
            new_name='annotation_link',
        ),
        migrations.RenameField(
            model_name='historicalannotation',
            old_name='reference_link_title',
            new_name='annotation_link_title',
        ),
        migrations.AlterUniqueTogether(
            name='annotationupvote',
            unique_together=set([('user', 'annotation')]),
        ),
        migrations.AlterField(
            model_name='annotationreport',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_reports',
                                    to='annotation.Annotation'),
        ),
    ]
