# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0020_set_url_length_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_link_title',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'normalny'), ('WARNING', 'ostrzegawczy'), ('ALERT', 'niebezpieczny')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='annotation_link_title',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'normalny'), ('WARNING', 'ostrzegawczy'), ('ALERT', 'niebezpieczny')], max_length=10),
        ),
    ]
