# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 14:26
from __future__ import unicode_literals

from django.utils.crypto import get_random_string
from django.conf import settings
from django.db import migrations
from django.contrib.auth.hashers import make_password


def insert_demagog_user(apps, schema):
    user_model = apps.get_model(settings.AUTH_USER_MODEL)
    user_model(username=settings.DEMAGOG_USERNAME, password=make_password(get_random_string(length=32))).save()


class Migration(migrations.Migration):
    dependencies = [
        ('annotation', '0023_add_publisher_quotecontext'),
    ]

    operations = [
        migrations.RunPython(insert_demagog_user, lambda apps, schema: None),
    ]
