version: '3.5'

services:
  web:
    depends_on:
      - postgres
      - redis
    image: pp/python-venv
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./docker/venv:/opt/venv
    env_file:
      - ./dev.env
      - ./dev-local.env
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    depends_on:
      - postgres
      - redis
    image: pp/python-venv
    volumes:
      - .:/code
      - ./docker/venv:/opt/venv
    env_file:
      - ./dev.env
      - ./dev-local.env
    command: celery worker --app=worker.celery_app --loglevel=info --concurrency=2

  worker_beat:
    depends_on:
      - redis
    image: pp/python-venv
    volumes:
      - .:/code
      - ./docker/venv:/opt/venv
    env_file:
      - ./dev.env
    command: >
      celery beat --app=worker.celery_app --loglevel=info
      --schedule=/home/user/celerybeat.db --pidfile=/home/user/celerybeat.pid

  redis:
    image: "redis:alpine"
    volumes:
      - ./docker/data/redis:/data

  postgres:
    image: "postgres:10-alpine"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    env_file:
      - ./dev.env
