version: 2
jobs:
  build:
    docker:
      - image: python:3.6
    environment:
      PP_SECRET_KEY: dummy
      ENV: test

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: create venv
          command: |
            python -m venv venv
            . venv/bin/activate

      - restore_cache:
          keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - pip-packages-v2-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test -v 2

      - save_cache:
          paths:
            - ~/project/venv  # this path depends on where pipenv creates a virtualenv
          key: pip-packages-v2-{{ checksum "requirements.txt" }}
