# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pp', '0025_add_annotation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(choices=[('PP', 'Przypis Powszechny'), ('DEMAGOG', 'Demagog')], db_index=True, max_length=10)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('original_data', models.TextField(max_length=10000)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAnnotationOrigin',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, editable=False)),
                ('publisher', models.CharField(choices=[('PP', 'Przypis Powszechny'), ('DEMAGOG', 'Demagog')], db_index=True, max_length=10)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('original_data', models.TextField(max_length=10000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('annotation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='annotation.Annotation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical annotation origin',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
