# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationorigin',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='historicalannotationorigin',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='historicalannotationorigin',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='AnnotationOrigin',
        ),
        migrations.DeleteModel(
            name='HistoricalAnnotationOrigin',
        ),
    ]
