# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 03:26
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_reference_add_count_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='objection_count',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='useful_count',
        ),
        migrations.AlterField(
            model_name='userreferencefeedback',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pp.Reference'),
        ),
    ]
