# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0003_remove_useful_objection_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='range',
            new_name='ranges',
        ),
        migrations.RenameField(
            model_name='referencerequest',
            old_name='range',
            new_name='ranges',
        ),
    ]
