# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_rename_range_to_ranges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='link',
            new_name='reference_link',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='link_title',
            new_name='reference_link_title',
        ),
    ]
