# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0006_add_deleted_to_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReference',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, editable=False)),
                ('url', models.CharField(max_length=200)),
                ('ranges', models.TextField(max_length=1000)),
                ('quote', models.TextField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.CharField(
                    choices=[('NORMAL', 'normalny'), ('WARNING', 'ostrzegawczy'), ('ALERT', 'niebezpieczny')],
                    max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('reference_link', models.CharField(max_length=100)),
                ('reference_link_title', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('reference_request', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                        on_delete=django.db.models.deletion.DO_NOTHING,
                                                        related_name='+', to='pp.ReferenceRequest')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical reference',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
