# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0007_historicalreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('SPAM', 'spam'), ('OTHER', 'inne')], max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.Reference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
