# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0010_auto_20171228_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pp.ReferenceRequest'),
        ),
    ]
