# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0011_auto_20180426_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnnotationRequestFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='ReferenceRequest',
            new_name='AnnotationRequest',
        ),
        migrations.AlterUniqueTogether(
            name='userreferencerequestfeedback',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userreferencerequestfeedback',
            name='reference_request',
        ),
        migrations.RemoveField(
            model_name='userreferencerequestfeedback',
            name='user',
        ),
        migrations.RenameField(
            model_name='historicalreference',
            old_name='reference_request',
            new_name='annotation_request',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='reference_request',
            new_name='annotation_request',
        ),
        migrations.DeleteModel(
            name='UserReferenceRequestFeedback',
        ),
        migrations.AddField(
            model_name='userannotationrequestfeedback',
            name='annotation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.AnnotationRequest'),
        ),
        migrations.AddField(
            model_name='userannotationrequestfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
