# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0012_auto_20180426_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('SPAM', 'spam'), ('OTHER', 'inne')], max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_reports', to='pp.Reference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='referencereport',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='referencereport',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReferenceReport',
        ),
    ]
