# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 22:00
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection


class Migration(migrations.Migration):
    atomic = connection.vendor is not 'sqlite'

    dependencies = [
        ('pp', '0014_rename_referenceupvote_to_annotationupvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnnotationRequestFeedback',
            new_name='AnnotationRequestFeedback',
        ),
    ]
