# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0016_auto_20180426_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='reference_link',
            new_name='annotation_link',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='reference_link_title',
            new_name='annotation_link_title',
        ),
        migrations.RenameField(
            model_name='annotationreport',
            old_name='reference',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='annotationupvote',
            old_name='reference',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='historicalannotation',
            old_name='reference_link',
            new_name='annotation_link',
        ),
        migrations.RenameField(
            model_name='historicalannotation',
            old_name='reference_link_title',
            new_name='annotation_link_title',
        ),
        migrations.AlterUniqueTogether(
            name='annotationupvote',
            unique_together=set([('user', 'annotation')]),
        ),
    ]
