# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0017_rename_all_annotation_related_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='ranges',
            new_name='range',
        ),
        migrations.RenameField(
            model_name='annotationrequest',
            old_name='ranges',
            new_name='range',
        ),
        migrations.RenameField(
            model_name='historicalannotation',
            old_name='ranges',
            new_name='range',
        ),
    ]
