# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0022_annotation_report_blank_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='publisher',
            field=models.CharField(choices=[('PP', 'Przypis Powszechny'), ('DEMAGOG', 'Demagog')], default='PP',
                                   max_length=10),
        ),
        migrations.AddField(
            model_name='annotation',
            name='quote_context',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='annotationrequest',
            name='quote_context',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='publisher',
            field=models.CharField(choices=[('PP', 'Przypis Powszechny'), ('DEMAGOG', 'Demagog')], default='PP',
                                   max_length=10),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='quote_context',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='range',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='annotationreport',
            name='reason',
            field=models.CharField(
                choices=[('BIASED', 'nieobiektywny'), ('UNRELIABLE', 'nierzetelne źródło'), ('USELESS', 'niepotrzebny'),
                         ('SPAM', 'spam'), ('OTHER', 'inne'), ('SUGGESTED_CORRECTION', 'sugerowana poprawka')],
                max_length=100),
        ),
        migrations.AlterField(
            model_name='annotationrequest',
            name='range',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='range',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
