# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-15 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def insert_demagog_user(apps, schema):
    annotation_model = apps.get_model('pp.Annotation')
    historical_annotation_model = apps.get_model('pp.HistoricalAnnotation')
    annotation_model.objects.update(category=F('priority'))
    historical_annotation_model.objects.update(category=F('priority'))


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0024_insert_demagog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='category',
            field=models.CharField(choices=[('NORMAL', 'normalny'), ('WARNING', 'ostrzegawczy'), ('ALERT', 'niebezpieczny')], default='unset', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='category',
            field=models.CharField(choices=[('NORMAL', 'normalny'), ('WARNING', 'ostrzegawczy'), ('ALERT', 'niebezpieczny')], default='unset', max_length=10),
            preserve_default=False,
        ),
        migrations.RunPython(insert_demagog_user, lambda apps, schema: None),
    ]
