# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-15 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0025_add_annotation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAnnotationOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(choices=[('PP', 'Przypis Powszechny'), ('DEMAGOG', 'Demagog')], db_index=True, max_length=10)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('original_data', models.TextField(max_length=10000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='externalannotationorigin',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.Annotation'),
        ),
        migrations.AddField(
            model_name='externalannotationorigin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
