# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('pp', '0025_add_annotation_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='annotation',
                    table='annotation_annotation',
                ),
                migrations.AlterModelTable(
                    name='historicalannotation',
                    table='annotation_historicalannotation',
                ),
                migrations.AlterModelTable(
                    name='annotationreport',
                    table='annotation_annotationreport',
                ),
                migrations.AlterModelTable(
                    name='annotationrequest',
                    table='annotation_annotationrequest',
                ),
                migrations.AlterModelTable(
                    name='annotationrequestfeedback',
                    table='annotation_annotationrequestfeedback',
                ),
                migrations.AlterModelTable(
                    name='annotationupvote',
                    table='annotation_annotationupvote',
                ),
                # migrations.AlterModelTable(
                #     name='user',
                #     table='user_user',
                # ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='annotation',
                    name='annotation_request',
                ),
                migrations.RemoveField(
                    model_name='annotation',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='annotationreport',
                    name='annotation',
                ),
                migrations.RemoveField(
                    model_name='annotationreport',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='annotationrequest',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='annotationrequestfeedback',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='annotationrequestfeedback',
                    name='annotation_request',
                ),
                migrations.RemoveField(
                    model_name='annotationrequestfeedback',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='annotationupvote',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='annotationupvote',
                    name='annotation',
                ),
                migrations.RemoveField(
                    model_name='annotationupvote',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='historicalannotation',
                    name='annotation_request',
                ),
                migrations.RemoveField(
                    model_name='historicalannotation',
                    name='history_user',
                ),
                migrations.RemoveField(
                    model_name='historicalannotation',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Annotation',
                ),
                migrations.DeleteModel(
                    name='AnnotationReport',
                ),
                migrations.DeleteModel(
                    name='AnnotationRequest',
                ),
                migrations.DeleteModel(
                    name='AnnotationRequestFeedback',
                ),
                migrations.DeleteModel(
                    name='AnnotationUpvote',
                ),
                migrations.DeleteModel(
                    name='HistoricalAnnotation',
                ),
                # migrations.DeleteModel(
                #     name='User',
                # ),
            ],
        ),
    ]
