# Generated by Django 2.0.13 on 2019-03-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0026_rename_and_remove_all'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('editor', 'editor'), ('reader', 'reader')], default='reader', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
