# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-18 00:46
from __future__ import unicode_literals

from django.db import migrations, models

NORMAL = 'NORMAL'
WARNING = 'WARNING'
ALERT = 'ALERT'

ADDITIONAL_INFO = 'ADDITIONAL_INFO'
CLARIFICATION = 'CLARIFICATION'
ERROR = 'ERROR'


def reverse_init_priority(apps, schema):
    annotation_model = apps.get_model('annotation.Annotation')
    historical_annotation_model = apps.get_model('annotation.HistoricalAnnotation')

    annotation_model.objects.filter(pp_category=ADDITIONAL_INFO).update(priority=NORMAL)
    annotation_model.objects.filter(pp_category=CLARIFICATION).update(priority=WARNING)
    annotation_model.objects.filter(pp_category=ERROR).update(priority=ALERT)

    historical_annotation_model.objects.filter(pp_category=ADDITIONAL_INFO).update(priority=NORMAL)
    historical_annotation_model.objects.filter(pp_category=CLARIFICATION).update(priority=WARNING)
    historical_annotation_model.objects.filter(pp_category=ERROR).update(priority=ALERT)


class Migration(migrations.Migration):
    dependencies = [
        ('annotation', '0002_add_categories_pp_dg'),
    ]

    operations = [

        migrations.RunPython(migrations.RunPython.noop, reverse_init_priority),

        migrations.AlterField(
            model_name='annotation',
            name='priority',
            field=models.CharField(
                default='non',
                choices=[('NORMAL', 'normalny'), ('WARNING', 'ostrzegawczy'), ('ALERT', 'niebezpieczny')],
                max_length=10),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='priority',
            field=models.CharField(
                default='non',
                choices=[('NORMAL', 'normalny'), ('WARNING', 'ostrzegawczy'), ('ALERT', 'niebezpieczny')],
                max_length=10),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicalannotation',
            name='priority',
        ),
    ]
