# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-18 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_add_categories_pp_dg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicalannotation',
            name='priority',
        ),
    ]
