# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-18 01:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

ADDITIONAL_INFO = 'ADDITIONAL_INFO'
CLARIFICATION = 'CLARIFICATION'
ERROR = 'ERROR'

TRUE = 'TRUE'
PTRUE = 'PTRUE'
FALSE = 'FALSE'
PFALSE = 'PFALSE'
LIE = 'LIE'
UNKOWN = 'UNKNOWN'

PP_PUBLISHER = 'PP'
DEMAGOG_PUBLISHER = 'DEMAGOG'


def insert_mock_annotation(apps, schema):
    annotation_model = apps.get_model('annotation.Annotation')
    user_model = apps.get_model(settings.AUTH_USER_MODEL)

    url = 'https://www.polskieradio.pl/13/53/Artykul/2175283,' \
          'Sygnaly-Dnia-6-sierpnia-2018-roku-rozmowa-z-Andrzejem-Halickim',

    if annotation_model.objects.filter(url=url, publisher=DEMAGOG_PUBLISHER).exists():
        return

    annotation_model.objects.create(
        user=user_model.objects.filter(username=settings.DEMAGOG_USERNAME).first(),
        publisher=DEMAGOG_PUBLISHER,
        url=url,
        pp_category=ADDITIONAL_INFO,
        demagog_category=TRUE,
        quote='Jeżeli policjant (to jest ustawa o Policji) dostanie od przełożonego rozkaz, który jest sprzeczny z '
              'prawem, ma obowiązek, nie tylko powinien, ale ma obowiązek odmówić wykonania rozkazu.',
        annotation_link='http://demagog.org.pl/wypowiedzi/andrzej-halicki-w-sygnalach-dnia/',
        annotation_link_title='demagog.org.pl'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('annotation', '0003_remove_priority'),
    ]

    operations = [
        migrations.RunPython(insert_mock_annotation, migrations.RunPython.noop)
    ]
