# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_insert_demagog_mock_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='publisher_annotation_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='publisher_annotation_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='annotationreport',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='annotationrequest',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='annotationupvote',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
