# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('annotation', '0009_add_annotation_check_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationrequest',
            name='quote_context',
        ),
        migrations.RemoveField(
            model_name='annotationrequest',
            name='range',
        ),
        migrations.AddField(
            model_name='annotationrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='annotationrequest',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='annotationrequest',
            name='quote',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
