# Generated by Django 2.0.13 on 2019-05-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_add_annotation_request_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationrequest',
            name='quote_context',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='annotationrequest',
            name='range',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='annotationrequest',
            name='quote',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='annotationupvote',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Annotation'),
        ),
    ]
