# Generated by Django 2.0.13 on 2019-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_add_annotation_request_quote_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='range',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='annotationrequest',
            name='range',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='range',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
